/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import gson.BaiHat;
import gson.Casi;
import java.awt.Color;
import javax.swing.ImageIcon;
import services.utils;
import view.MainJFrame;

/**
 *
 * @author tranv
 */
public class ItemMVPanel extends javax.swing.JPanel {

    BaiHat bh;
    /**
     * Creates new form ItemMVPanel
     */
    public ItemMVPanel(BaiHat bh) {
        initComponents();
        
        this.bh = bh;
        
        if(bh == null){
            setBackground(new Color(23,15,35));
            imgBaiHat.setIcon(null);
            imgBaiHat.setBackground(new Color(23,15,35));
            imgBaiHat.setEnabled(false);
            lbTenBaiHat.setText("");
            lbTenCaSi.setText("");
            imgCaSi.setIcon(null);
        }
        else {
            ImageIcon img = utils.getImageBaiHat(bh.getAnhBia(), 400, 400);
            imgBaiHat.setIcon(img);
            lbTenBaiHat.setText(bh.getTenBaiHat());
            lbTenCaSi.setText(utils.getTenCaSi(bh));
            
            Casi cs = bh.getBaiHat_caSis().get(0).getCasi();
            ImageIcon img2 = utils.getImageBaiHat(cs.getAnh(), 50, 50);
            imgCaSi.setIcon(img2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgBaiHat = new javax.swing.JButton();
        imgCaSi = new javax.swing.JLabel();
        lbTenBaiHat = new javax.swing.JLabel();
        lbTenCaSi = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 15, 35));

        imgBaiHat.setBackground(new java.awt.Color(0, 0, 0));
        imgBaiHat.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\anh-bia-am-nhac2.jpg")); // NOI18N
        imgBaiHat.setBorder(null);
        imgBaiHat.setFocusPainted(false);
        imgBaiHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBaiHatActionPerformed(evt);
            }
        });

        imgCaSi.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\anh-bia-am-nhac2.jpg")); // NOI18N

        lbTenBaiHat.setForeground(new java.awt.Color(255, 255, 255));
        lbTenBaiHat.setText("Ten bai hat");

        lbTenCaSi.setForeground(new java.awt.Color(153, 153, 153));
        lbTenCaSi.setText("Ten ca si");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenBaiHat)
                            .addComponent(lbTenCaSi))
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addComponent(imgBaiHat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTenBaiHat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTenCaSi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgBaiHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBaiHatActionPerformed
        // TODO add your handling code here:
        if(bh != null ) {
            System.out.println("id bai Hat: "+bh.getId());
            System.out.println("link mv: "+bh.getLinkMV());
            
            if(MainJFrame.historyPanel.peek().equals("ChiTietMV")) {
                ChiTietMVPanel.idMV = bh.getId();
                MainJFrame.resetPanel();
            }
            else {
                MainJFrame.ShowPanel("ChiTietMV", new ChiTietMVPanel(bh.getId()));
            }
            
            
        }
        
    }//GEN-LAST:event_imgBaiHatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imgBaiHat;
    private javax.swing.JLabel imgCaSi;
    private javax.swing.JLabel lbTenBaiHat;
    private javax.swing.JLabel lbTenCaSi;
    // End of variables declaration//GEN-END:variables
}
