/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import javax.swing.JPanel;

/**
 *
 * @author tranv
 */
public class KhamPhaPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhamPha
     */
    public KhamPhaPanel() {
        initComponents();
        
        for (int i = 0; i < 10; i++) {
            JPanel pn = new ItemMusicPanel(i + 1, "Bai hat " + (i + 1), "Ten Ca Si " + (i + 1), "4:00");
            PanelMusicContainer.add(pn);
        }
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelMusicContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 51));
        setMinimumSize(new java.awt.Dimension(100, 100));

        jScrollPane1.setViewportView(PanelMusicContainer);

        PanelMusicContainer.setBackground(new java.awt.Color(0, 0, 51));
        PanelMusicContainer.setLayout(new javax.swing.BoxLayout(PanelMusicContainer, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PanelMusicContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMusicContainer;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
