/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tranv
 */
public class LoadingTaiBaiHat extends javax.swing.JPanel {

    /**
     * Creates new form LoadingTaiBaiHat
     */
    public static Thread thread;

    public LoadingTaiBaiHat() {
        initComponents();

        thread = new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(200);
                    String text = lblLoading.getText();
                    if (text.equals("Loading.")) {
                        lblLoading.setText("Loading..");
                    } else if (text.equals("Loading..")) {
                        lblLoading.setText("Loading...");
                    } else if (text.equals("Loading...")) {
                        lblLoading.setText("Loading....");
                    } else if (text.equals("Loading....")) {
                        lblLoading.setText("Loading.");
                    }

                } catch (InterruptedException ex) {
                    break;
                }

            }
        });
        thread.start();

    }

    public static void closeThread() {
        if (thread != null && thread.isAlive()) {
            thread.interrupt();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lblLoading.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLoading.setText("Loading...");

        jLabel2.setText("Quá trình tải xuống đang diễn ra, bạn có thể đợi hoặc để chế độ nền.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoading)
                    .addComponent(jLabel2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoading)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables
}
