/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.awt.Color;

/**
 *
 * @author tranv
 */
public class TimKiemPanel extends javax.swing.JPanel {

    public static String typeSearch = "BaiHat";
    public static String keyword = "";
    /**
     * Creates new form TimKiemPanel
     */
    public TimKiemPanel(String keyword) {
        initComponents();
        
        TimKiemPanel.keyword = keyword;
        
        switchTypeSearch(typeSearch);
        
       
    }

    public void switchTypeSearch(String name) {
        typeSearch = name;
        switch (name) {
            case "BaiHat": {
                btnBaiHat.setBackground(new Color(204, 0, 204));
                btnNgheSi.setBackground(new Color(23, 15, 35));
                btnMV.setBackground(new Color(23, 15, 35));
                
                PanelContentSearch.removeAll();
                PanelContentSearch.add(new BaiHatSearchPanel(keyword));
                break;
            }
            case "NgheSi": {
                btnBaiHat.setBackground(new Color(23, 15, 35));
                btnNgheSi.setBackground(new Color(204, 0, 204));
                btnMV.setBackground(new Color(23, 15, 35));
                
                PanelContentSearch.removeAll();
                PanelContentSearch.add(new NgheSiSearchPanel(keyword));
                break;
            }
            case "MV": {
                btnBaiHat.setBackground(new Color(23, 15, 35));
                btnNgheSi.setBackground(new Color(23, 15, 35));
                btnMV.setBackground(new Color(204, 0, 204));
                
                PanelContentSearch.removeAll();
                PanelContentSearch.add(new MVSearchPanel(keyword));
                break;
            }
            default: {
                btnBaiHat.setBackground(new Color(204, 0, 204));
                btnNgheSi.setBackground(new Color(23, 15, 35));
                btnMV.setBackground(new Color(23, 15, 35));
                break;
            }
        }
        
        PanelContentSearch.revalidate();
        PanelContentSearch.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBaiHat = new javax.swing.JButton();
        btnNgheSi = new javax.swing.JButton();
        btnMV = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        PanelContentSearch = new javax.swing.JPanel();

        setBackground(new java.awt.Color(23, 15, 35));

        jPanel1.setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kết quả tìm kiếm");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBaiHat.setBackground(new java.awt.Color(23, 15, 35));
        btnBaiHat.setForeground(new java.awt.Color(255, 255, 255));
        btnBaiHat.setText("Bài hát");
        btnBaiHat.setFocusPainted(false);
        btnBaiHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaiHatActionPerformed(evt);
            }
        });

        btnNgheSi.setBackground(new java.awt.Color(23, 15, 35));
        btnNgheSi.setForeground(new java.awt.Color(255, 255, 255));
        btnNgheSi.setText("Nghệ sĩ");
        btnNgheSi.setFocusPainted(false);
        btnNgheSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgheSiActionPerformed(evt);
            }
        });

        btnMV.setBackground(new java.awt.Color(23, 15, 35));
        btnMV.setForeground(new java.awt.Color(255, 255, 255));
        btnMV.setText("MV");
        btnMV.setFocusPainted(false);
        btnMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMVActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBaiHat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNgheSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMV)
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBaiHat)
                        .addComponent(btnNgheSi)
                        .addComponent(btnMV))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelContentSearch.setBackground(new java.awt.Color(23, 15, 35));
        PanelContentSearch.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelContentSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelContentSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaiHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaiHatActionPerformed
        // TODO add your handling code here:
        switchTypeSearch("BaiHat");
    }//GEN-LAST:event_btnBaiHatActionPerformed

    private void btnNgheSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgheSiActionPerformed
        // TODO add your handling code here:
        switchTypeSearch("NgheSi");
    }//GEN-LAST:event_btnNgheSiActionPerformed

    private void btnMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMVActionPerformed
        // TODO add your handling code here:
        switchTypeSearch("MV");
    }//GEN-LAST:event_btnMVActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContentSearch;
    private javax.swing.JButton btnBaiHat;
    private javax.swing.JButton btnMV;
    private javax.swing.JButton btnNgheSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
