/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameduoihinhbatchu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import services.MySql;
import helpers.Utils;

/**
 *
 * @author tranv
 */
public class QuanLyCauHoi extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    String idCauHoi = "";

    /**
     * Creates new form QuanLyCauHoi
     */
    public QuanLyCauHoi() {
        initComponents();

        //lay ds
        layDanhSachCauHoi();

        //set event table
        setEventTable();

        lbAnh.setVisible(false);
    }

    public void layDanhSachCauHoi() {

        try {
            model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Ảnh");
            model.addColumn("Đáp án");
            jTable1.setModel(model);

            String sqlLayCauHoi = "SELECT * FROM CauHoi";
            ResultSet kq = MySql.queryData(sqlLayCauHoi);

            while (kq != null && kq.next()) {
                Object[] data1 = {kq.getString("Id"), kq.getString("Anh"), kq.getString("DapAn")};
                model.addRow(data1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setEventTable() {
        ListSelectionModel selectionModel = jTable1.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Xử lý sự kiện khi lựa chọn dòng
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow != -1) {
                        // Lấy dữ liệu từ dòng đã chọn
                        idCauHoi = (String) model.getValueAt(selectedRow, 0);
                        String anh = (String) model.getValueAt(selectedRow, 1);
                        String dapAn = (String) model.getValueAt(selectedRow, 2);

                        // Hiển thị thông tin
                        tfAnh.setText(anh);
                        tfDapAn.setText(dapAn);

                        //set button
                        btnThem.setEnabled(false);
                        btnLuu.setEnabled(true);
                        btnHuy.setEnabled(true);
                        btnXoa.setEnabled(true);

                        //gán ảnh
                        new Thread(() -> {
                            try {
                                ImageIcon anhIcon = Utils.layImageIcon(anh, 70, 70);
                                lbAnh.setIcon(anhIcon);
                                lbAnh.setVisible(true);
                            } catch (Exception ex) {
                                System.out.println("URL Không hợp lệ");
                            }

                        }).start();

                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfAnh = new javax.swing.JTextField();
        tfDapAn = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý câu hỏi");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ảnh:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Đáp án:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.setEnabled(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLuu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHuy))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbAnh)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAnh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        xuLyThem();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        //set button
        btnThem.setEnabled(true);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
        btnXoa.setEnabled(false);

        tfAnh.setText("");
        tfDapAn.setText("");
        idCauHoi = "";

        jTable1.clearSelection();
        
        lbAnh.setVisible(false);

    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int xacnhan = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa?", "",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (xacnhan == JOptionPane.OK_OPTION) {
            xuLyXoa();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        xulyLuu();
    }//GEN-LAST:event_btnLuuActionPerformed

    public void xulyLuu() {
        if (idCauHoi.isEmpty()) {
            return;
        }

        String anh = tfAnh.getText();
        String dapAn = tfDapAn.getText();

        if (anh.isEmpty() || dapAn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Dữ liệu không được để trống!");
            return;
        }

        String sqlSua = String.format("UPDATE CauHoi SET Anh = '%s', DapAn = '%s' WHERE Id = '%s'", anh, dapAn, idCauHoi);
        int kq = MySql.excuteQuery(sqlSua);
        if (kq != 0) {
            idCauHoi = "";
            tfAnh.setText("");
            tfDapAn.setText("");

            //lay ds cau hoi
            layDanhSachCauHoi();
            
            lbAnh.setVisible(false);
            
             //set btn
            btnThem.setEnabled(true);
            btnLuu.setEnabled(false);
            btnHuy.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Sửa thất bại");
        }
    }

    public void xuLyXoa() {
        if (idCauHoi.isEmpty()) {
            return;
        }

        String sqlXoa = String.format("DELETE FROM CauHoi WHERE Id = '%s'", idCauHoi);

        int kq = MySql.excuteQuery(sqlXoa);
        if (kq != 0) {
            tfAnh.setText("");
            tfDapAn.setText("");
            idCauHoi = "";

            //set btn
            btnThem.setEnabled(true);
            btnLuu.setEnabled(false);
            btnHuy.setEnabled(false);
            btnXoa.setEnabled(false);

            //lay ds cau hoi
            layDanhSachCauHoi();
            
            lbAnh.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }

    }

    public void xuLyThem() {
        String anh = tfAnh.getText();
        String dapAn = tfDapAn.getText();

        if (anh.isEmpty() || dapAn.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Phải nhập đủ thông tin!");
            return;
        }

        String id = Utils.randomId();
        String sqlThem = String.format("InSERT INTO CauHoi(Id,Anh,DapAn) VALUES ('%s','%s','%s')", id, anh, dapAn);

        int kq = MySql.excuteQuery(sqlThem);
        if (kq != 0) {
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            tfAnh.setText("");
            tfDapAn.setText("");

            //lay ds cau hoi
            layDanhSachCauHoi();
        } else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JTextField tfAnh;
    private javax.swing.JTextField tfDapAn;
    // End of variables declaration//GEN-END:variables
}
