/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameduoihinhbatchu;

import frame.Main;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import services.MySql;
import helpers.Utils;

//làm HD ảnh: https://picwish.com/vn/photo-enhancer
//tải ảnh lấy url: https://postimg.cc/


public class TrangChu extends javax.swing.JFrame {

    ArrayList<String> listIdCauHoi = new ArrayList<>();
    String DapAn = "";
    int diem = 0;

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        lbAnh.setVisible(false);
        tfDapAn.setVisible(false);
        lbDiem.setVisible(false);
        btnChoiLai.setVisible(false);
        btnOK.setVisible(false);

    }

    public void layCauHoi() {

        try {
            lbAnh.setText("Đang tải...");
            lbAnh.setIcon(null);
            String sql = "SELECT * FROM CauHoi ";
            if (!listIdCauHoi.isEmpty()) {
                String listId = "WHERE Id NOT IN (";
                int size = listIdCauHoi.size();
                for (int i = 0; i < size; i++) {
                    if (i != 0) {
                        listId += ", ";
                    }
                    listId += "'" + listIdCauHoi.get(i) + "'";
                }
                listId += ")";

                sql += listId;
            }

            sql += "ORDER BY RAND() LIMIT 1";

            ResultSet kq = MySql.queryData(sql);
            while (kq != null && kq.next()) {
                String id = kq.getString("Id");
                String anh = kq.getString("Anh");
                DapAn = kq.getString("DapAn");

                new Thread(() -> {
                    ImageIcon anhIcon = Utils.layImageIcon(anh, 100, 100);
                    lbAnh.setIcon(anhIcon);
                    lbAnh.setText("");
                }).start();

                listIdCauHoi.add(id);
                return;
            }

            int xacnhan = JOptionPane.showConfirmDialog(null, "Đã hết câu hỏi, điểm tối đa của bạn là: " + diem + "\nBạn có muốn chơi lại không?", "Xin chúc mừng",
                    JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (xacnhan == JOptionPane.OK_OPTION) {
                xuLyChoiLai();
            } else {
                Main.rootFrame.setVisible(true);
                dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnChoi = new javax.swing.JButton();
        lbDiem = new javax.swing.JLabel();
        lbAnh = new javax.swing.JLabel();
        tfDapAn = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnChoiLai = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đuổi hình bắt chữ");

        btnChoi.setText("Chơi");
        btnChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiActionPerformed(evt);
            }
        });

        lbDiem.setText("Điểm: 0");

        lbAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfDapAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDapAnActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnChoiLai.setText("Chơi lại");
        btnChoiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiLaiActionPerformed(evt);
            }
        });

        jMenu1.setText("Admin");

        jMenuItem1.setText("Quản lý câu hỏi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChoiLai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(lbDiem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoi)
                    .addComponent(lbDiem)
                    .addComponent(btnChoiLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DangNhap dangNhap = new DangNhap();
        dangNhap.setVisible(true);
        dangNhap.setLocationRelativeTo(null);
        dangNhap.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

//        dangNhap.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosed(WindowEvent e) {
//                setVisible(true);
//            }
//        
//        });
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiActionPerformed
        // TODO add your handling code here:
        lbAnh.setVisible(true);
        tfDapAn.setVisible(true);
        lbDiem.setVisible(true);

        layCauHoi();

        btnChoi.setVisible(false);
        btnChoiLai.setVisible(true);
        btnOK.setVisible(true);

    }//GEN-LAST:event_btnChoiActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        xuLyOK();


    }//GEN-LAST:event_btnOKActionPerformed

    public void xuLyOK() {
        String strDapAn = tfDapAn.getText();
        if (strDapAn.isEmpty()) {
            return;
        }

        if (DapAn.equals(strDapAn)) {

            diem++;

            lbDiem.setText("Điểm: " + diem);

            tfDapAn.setText("");
            layCauHoi();

        } else {
            JOptionPane.showMessageDialog(null, "Đáp án không chính xác!");
        }
    }

    private void tfDapAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDapAnActionPerformed
        // TODO add your handling code here:
        xuLyOK();
    }//GEN-LAST:event_tfDapAnActionPerformed

    private void btnChoiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiLaiActionPerformed
        // TODO add your handling code here:

        xuLyChoiLai();

    }//GEN-LAST:event_btnChoiLaiActionPerformed

    public void xuLyChoiLai() {
        diem = 0;
        lbDiem.setText("Điểm: " + diem);
        tfDapAn.setText("");

        listIdCauHoi = new ArrayList<>();

        layCauHoi();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoi;
    private javax.swing.JButton btnChoiLai;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbDiem;
    private javax.swing.JTextField tfDapAn;
    // End of variables declaration//GEN-END:variables
}
