/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import component.ItemMusicPanel;
import gson.BaiHat;
import gson.TimKiemBaiHat;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import services.ApiServiceV1;

/**
 *
 * @author tranv
 */
public class BaiHatSearchPanel extends javax.swing.JPanel {
    
    public static ArrayList<BaiHat> dsBaiHat;

    /**
     * Creates new form BaiHatSearchPanel
     */
    public BaiHatSearchPanel(String keyword) {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        handleTimBaiHat(keyword);
    }

    public void handleTimBaiHat(String keyword) {

        ApiServiceV1.apiServiceV1.timKiemBaiHat(keyword, "0", "10").enqueue(new Callback<TimKiemBaiHat>() {
            @Override
            public void onResponse(Call<TimKiemBaiHat> call, Response<TimKiemBaiHat> rspns) {
                PanelContainerMusic.removeAll();
                TimKiemBaiHat res = rspns.body();
                if (res != null && res.getErrCode() == 0) {

                    dsBaiHat = new ArrayList<>();
                    
                    new Thread(() -> {
                        int size = res.getData().size();
                        for (int i = 0; i < size; i++) {
                            BaiHat bh = res.getItemIndex(i);
                            JPanel pnBaiHat = new ItemMusicPanel(bh, i + 1, "timKiem");
                            PanelContainerMusic.add(pnBaiHat, BorderLayout.CENTER);
                            
                            dsBaiHat.add(bh);
                        }
                        PanelContainerMusic.revalidate();
                        PanelContainerMusic.repaint();
                    }).start();

                } else {
                    System.out.println("KO tim thay bai hat");
                }
            }

            @Override
            public void onFailure(Call<TimKiemBaiHat> call, Throwable thrwbl) {
                System.out.println("Error tim bai hat");
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelContainerMusic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bài hát");

        jScrollPane1.setBorder(null);

        PanelContainerMusic.setBackground(new java.awt.Color(23, 15, 35));
        PanelContainerMusic.setLayout(new javax.swing.BoxLayout(PanelContainerMusic, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đang tải...");
        PanelContainerMusic.add(jLabel2);

        jScrollPane1.setViewportView(PanelContainerMusic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(218, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContainerMusic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
