/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import component.CustomScrollBarUI;
import component.ItemLivePanel;
import gson.GetListLive;
import gson.LiveItem;
import java.util.ArrayList;
import javax.swing.JPanel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import services.ApiServiceV2;

/**
 *
 * @author tranv
 */
public class ListLivePanel extends javax.swing.JPanel {

    /**
     * Creates new form ListLivePanel
     */
    public ListLivePanel() {
        initComponents();
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());

//        ArrayList<LiveItem> listLive = new ArrayList<>();
//
//        for (int i = 0; i < 10; i++) {
//            LiveItem item = new LiveItem("id", "Ten" + i,
//                    "https://res.cloudinary.com/dultkpqjp/image/upload/v1683860764/avatar_user/no-user-image_axhl6d.png");
//            listLive.add(item);
//        }
//
//        for (LiveItem item : listLive) {
//            JPanel pn = new ItemLivePanel(item);
//            panelListLive.add(pn);
//        }
        handleGetListRoomLive();

    }

    public void handleGetListRoomLive() {

        ApiServiceV2.apiServiceV2.getListRoom().enqueue(new Callback<GetListLive>() {
            @Override
            public void onResponse(Call<GetListLive> call, Response<GetListLive> rspns) {
                GetListLive res = rspns.body();
                if (res != null && res.getErrCode() == 0) {
                    ArrayList<LiveItem> list = res.getData();

                    for (LiveItem item : list) {
                        JPanel pn = new ItemLivePanel(item);
                        panelListLive.add(pn);
                    }
                } else {
                    System.out.println("ko co phong live nao");
                }

            }

            @Override
            public void onFailure(Call<GetListLive> call, Throwable thrwbl) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListLive = new javax.swing.JPanel();

        setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Live");

        jScrollPane1.setBorder(null);

        panelListLive.setBackground(new java.awt.Color(23, 15, 35));
        panelListLive.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(panelListLive);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListLive;
    // End of variables declaration//GEN-END:variables
}
