/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import component.CustomScrollBarUI;
import component.WrapItemMVPanel;
import model.BaiHat;
import model.TimKiemMV;
import javax.swing.JPanel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import api.ApiServiceV1;

/**
 *
 * @author tranv
 */
public class MVSearch extends javax.swing.JPanel {

    /**
     * Creates new form BaiHatSearchPanel
     */
    public MVSearch(String keyword) {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        //test
        handleTimKiemMV(keyword);
    }

    public void handleTimKiemMV(String keyword) {

        ApiServiceV1.apiServiceV1.timKiemMV(keyword).enqueue(new Callback<TimKiemMV>() {
            @Override
            public void onResponse(Call<TimKiemMV> call, Response<TimKiemMV> rspns) {
                PanelContainer.removeAll();
                TimKiemMV res = rspns.body();
                if (res != null && res.getErrCode() == 0) {

                    int size = res.getData().size();
                    for (int i = 0; i < size; i = i + 2) {

                        if (i + 1 < size) {
                            BaiHat bh1 = res.getDataIndex(i);
                            BaiHat bh2 = res.getDataIndex(i + 1);

                            JPanel pn = new WrapItemMVPanel(bh1, bh2);
                            PanelContainer.add(pn);
                        } else {
                            BaiHat bh = res.getDataIndex(i);

                            JPanel pn = new WrapItemMVPanel(bh, null);
                            PanelContainer.add(pn);
                        }

                    }
                    PanelContainer.revalidate();
                    PanelContainer.repaint();
                } else {
                    System.out.println("Khong tim thay mv");
                }
            }

            @Override
            public void onFailure(Call<TimKiemMV> call, Throwable thrwbl) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MV");

        jScrollPane1.setBackground(new java.awt.Color(23, 15, 35));
        jScrollPane1.setBorder(null);

        PanelContainer.setBackground(new java.awt.Color(23, 15, 35));
        PanelContainer.setLayout(new javax.swing.BoxLayout(PanelContainer, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Đang tải...");
        PanelContainer.add(jLabel2);

        jScrollPane1.setViewportView(PanelContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
