/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import component.CustomScrollBarUI;
import component.ItemNgheSi;
import model.Casi;
import model.TimKiemCaSi;
import javax.swing.JPanel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import api.ApiServiceV1;

/**
 *
 * @author tranv
 */
public class NgheSiSearch extends javax.swing.JPanel {

    /**
     * Creates new form BaiHatSearchPanel
     */
    public NgheSiSearch(String keyword) {
        initComponents();

        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(20);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        handleTimCaSi(keyword);

    }

    public void handleTimCaSi(String keyword) {

        ApiServiceV1.apiServiceV1.timKiemCaSi(keyword, "0", "10").enqueue(new Callback<TimKiemCaSi>() {
            @Override
            public void onResponse(Call<TimKiemCaSi> call, Response<TimKiemCaSi> rspns) {
                PanelContainerNgheSi.removeAll();
                TimKiemCaSi res = rspns.body();
                if (res != null && res.getErrCode() == 0) {
                    int size = res.getData().size();
                    for (int i = 0; i < size; i++) {
                        Casi cs = res.getCaSiIndex(i);
                        JPanel pn = new ItemNgheSi(cs);
                        PanelContainerNgheSi.add(pn);
                    }
                    PanelContainerNgheSi.revalidate();
                    PanelContainerNgheSi.repaint();
                } else {
                    System.out.println("ko tim thay ca si");
                }

            }

            @Override
            public void onFailure(Call<TimKiemCaSi> call, Throwable thrwbl) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelContainerNgheSi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nghệ sĩ");

        jScrollPane1.setBackground(new java.awt.Color(23, 15, 35));
        jScrollPane1.setBorder(null);

        PanelContainerNgheSi.setBackground(new java.awt.Color(23, 15, 35));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        PanelContainerNgheSi.setLayout(flowLayout1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đang tải...");
        PanelContainerNgheSi.add(jLabel2);

        jScrollPane1.setViewportView(PanelContainerNgheSi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(355, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContainerNgheSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
