/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import api.ApiServiceV1;
import com.mysql.jdbc.Util;
import component.CustomScrollBarUI;
import component.ItemThongBao;
import frame.MainJFrame;
import helpers.Utils;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.LayDsThongBao;
import model.ThongBao;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author tranv
 */
public class ThongBaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongBao
     */
    private ArrayList<ThongBao> listThongBao;

    public ThongBaoPanel() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        getListThongBao();
        
    }

    public void getListThongBao() {
        pnListTB.removeAll();
        String header = Utils.getHeader();
        ApiServiceV1.apiServiceV1.layDanhSachTB(header).enqueue(new Callback<LayDsThongBao>() {
            @Override
            public void onResponse(Call<LayDsThongBao> call, Response<LayDsThongBao> rspns) {
                LayDsThongBao res = rspns.body();
                if (res != null && res.getErrCode() == 0) {
                    listThongBao = res.getData();
                    
                    for (ThongBao tb : listThongBao) {
                        JPanel pn = new ItemThongBao(tb);
                        pnListTB.add(pn);
                    }
                    pnListTB.revalidate();
                    pnListTB.repaint();
                }
                else {
                    System.out.println("không lay được data");
                }
            }

            @Override
            public void onFailure(Call<LayDsThongBao> call, Throwable thrwbl) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnListTB = new javax.swing.JPanel();

        jScrollPane1.setBorder(null);

        pnListTB.setBackground(new java.awt.Color(23, 15, 35));
        pnListTB.setLayout(new javax.swing.BoxLayout(pnListTB, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnListTB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnListTB;
    // End of variables declaration//GEN-END:variables
}
