/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screen;

import Interface.UpdateListMusic;
import component.CustomScrollBarUI;
import component.ItemMusic;
import model.BaiHat;
import model.GetListBHYeuThich;
import model.YeuThichBaiHat;
import java.util.ArrayList;
import javax.swing.JPanel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import api.ApiServiceV1;
import component.FilterListMusic;
import helpers.Utils;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tranv
 */
public class YeuThich extends javax.swing.JPanel implements UpdateListMusic {

    public static ArrayList<BaiHat> dsBaiHat;

    @Override
    public void updateListMusic() {
        PanelListMusic.removeAll();
        
        int size = dsBaiHat.size();
        for (int i = 0; i < size; i++) {
            BaiHat bh = dsBaiHat.get(i);
            JPanel pn = new ItemMusic(bh, i + 1, "YeuThich");
            PanelListMusic.add(pn);
        }
        PanelListMusic.revalidate();
        PanelListMusic.repaint();
    }

    public YeuThich() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        loadListMusic();
    }

    public void loadListMusic() {
        String header = Utils.getHeader();

        dsBaiHat = new ArrayList<>();
        ApiServiceV1.apiServiceV1.getListBHYeuThich("", "", header).enqueue(new Callback<GetListBHYeuThich>() {
            @Override
            public void onResponse(Call<GetListBHYeuThich> call, Response<GetListBHYeuThich> rspns) {
                GetListBHYeuThich res = rspns.body();
                if (res != null && res.getErrCode() == 0) {
                    PanelListMusic.removeAll();
                    ArrayList<YeuThichBaiHat> data = res.getData();
                    int size = data.size();
                    for (int i = 0; i < size; i++) {
                        BaiHat bh = data.get(i).getBaihat();
                        dsBaiHat.add(bh);
                        JPanel pn = new ItemMusic(bh, i + 1, "YeuThich");
                        PanelListMusic.add(pn);
                    }
                    PanelListMusic.revalidate();
                    PanelListMusic.repaint();
                    
                    pnFilter.removeAll();
                    pnFilter.add(new FilterListMusic(dsBaiHat, YeuThich.this));
                    pnFilter.revalidate();
                    pnFilter.repaint();
                } else {
                    System.out.println("ko tim thay ds bai hat yeu thich");
                }
            }

            @Override
            public void onFailure(Call<GetListBHYeuThich> call, Throwable thrwbl) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelListMusic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnFilter = new javax.swing.JPanel();

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(23, 15, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bài hát yêu thích");

        PanelListMusic.setBackground(new java.awt.Color(23, 15, 35));
        PanelListMusic.setLayout(new javax.swing.BoxLayout(PanelListMusic, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Đang tải...");
        PanelListMusic.add(jLabel2);

        pnFilter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelListMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 110, Short.MAX_VALUE))
            .addComponent(pnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelListMusic, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelListMusic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnFilter;
    // End of variables declaration//GEN-END:variables

}
