/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import panels.ChiTietCaSiPanel;
import panels.KaraokePanel;
import panels.KhamPhaPanel;
import panels.LivePanel;
import panels.NoiBatPanel;
import panels.PhatKeTiepPanel;
import panels.ThuVienPanel;
import panels.TimKiemPanel;
import services.MyMusicPlayer;

/**
 *
 * @author tranv
 */
public class MainJFrame extends javax.swing.JFrame {

    public static JPanel cardPanel;
    public static CardLayout cardLayout;
    public static boolean isMenuPhatKeTiep = false;
    public static boolean isKaraoke = false;
    public static String currentPanel = "";
    public static String oldPanel = "";

    /**
     * Creates new form HomeJFrame
     */
    public MainJFrame() {
        initComponents();

        initPanelContent();

//        PanelFooter.setVisible(false);

    }

    public void initPanelContent() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        // add panel
        cardPanel.add(new ChiTietCaSiPanel("017fb312-e04d-4755-9a08-d30ebbbc937a"), "ChiTietCaSi");
        cardPanel.add(new JPanel(), "ThuVien");
        cardPanel.add(new JPanel(), "Live");

        currentPanel = "ChiTietCaSi";

        // add vao Frame
        PanelContent.add(cardPanel, BorderLayout.CENTER);
    }

    public static void ShowPanel(String name, JPanel pn) {
        oldPanel = currentPanel;
        currentPanel = name;
        isKaraoke = false;

        ImageIcon icon = new ImageIcon(MainJFrame.class.getResource("/icon/micro.png"));
        btnKaraoke.setIcon(icon);

        JPanel newPN = pn;
        if (pn == null) {
            switch (name) {
                case "KhamPha":
                    newPN = new KhamPhaPanel();
                    break;
                case "ThuVien":
                    newPN = new ThuVienPanel();
                    break;
                case "Live":
                    newPN = new LivePanel();
                    break;
                case "Karaoke":
                    newPN = new KaraokePanel();
                    break;
                case "NoiBat":
                    newPN = new NoiBatPanel();
                    break;
                case "TimKiem":
                    newPN = new TimKiemPanel(TimKiemPanel.keyword);
                    break;
                case "ChiTietCaSi":
                    newPN = new ChiTietCaSiPanel(ChiTietCaSiPanel.idCaSi);
                    break;
                default:
                    newPN = new KhamPhaPanel();
            }
        }

        cardPanel.add(newPN, name);
        cardLayout.show(cardPanel, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelTabBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKhamPha = new javax.swing.JButton();
        btnThuVien = new javax.swing.JButton();
        btnLive = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnNoiBat = new javax.swing.JButton();
        PanelFooter = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imageBaiHat = new javax.swing.JLabel();
        lbTenBaiHat = new javax.swing.JLabel();
        lbTenCaSi = new javax.swing.JLabel();
        btnMore = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbThoiGianHienTai = new javax.swing.JLabel();
        lbTongThoiGian = new javax.swing.JLabel();
        progessTimeBaiHat = new javax.swing.JProgressBar();
        btnRandom = new javax.swing.JButton();
        btnLoop = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnPrevBaiHat = new javax.swing.JButton();
        btnPlayPause = new javax.swing.JButton();
        btnNextMusic = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        progessVolume = new javax.swing.JProgressBar();
        jButton13 = new javax.swing.JButton();
        btnMenuPhatKeTiep = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnKaraoke = new javax.swing.JButton();
        PannelContainer = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ipTimKiem = new javax.swing.JTextField();
        PanelWrap = new javax.swing.JPanel();
        PanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 800));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelTabBar.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\anh-bia-am-nhac2.jpg")); // NOI18N
        jLabel1.setText("  Music App");

        btnKhamPha.setBackground(new java.awt.Color(102, 102, 102));
        btnKhamPha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnKhamPha.setForeground(new java.awt.Color(255, 255, 255));
        btnKhamPha.setText("Khám phá");
        btnKhamPha.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnKhamPha.setBorderPainted(false);
        btnKhamPha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhamPha.setFocusPainted(false);
        btnKhamPha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhamPhaActionPerformed(evt);
            }
        });

        btnThuVien.setBackground(new java.awt.Color(51, 0, 51));
        btnThuVien.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnThuVien.setForeground(new java.awt.Color(255, 255, 255));
        btnThuVien.setText("Thư viện");
        btnThuVien.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnThuVien.setBorderPainted(false);
        btnThuVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThuVien.setFocusPainted(false);
        btnThuVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuVienActionPerformed(evt);
            }
        });

        btnLive.setBackground(new java.awt.Color(51, 0, 51));
        btnLive.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnLive.setForeground(new java.awt.Color(255, 255, 255));
        btnLive.setText("Live");
        btnLive.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnLive.setBorderPainted(false);
        btnLive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLive.setFocusPainted(false);
        btnLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiveActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 0, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Nhạc đã tải");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);

        jButton6.setBackground(new java.awt.Color(51, 0, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Yêu  thích");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);

        btnNoiBat.setBackground(new java.awt.Color(51, 0, 51));
        btnNoiBat.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnNoiBat.setForeground(new java.awt.Color(255, 255, 255));
        btnNoiBat.setText("Nổi bật");
        btnNoiBat.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnNoiBat.setBorderPainted(false);
        btnNoiBat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoiBat.setFocusPainted(false);
        btnNoiBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiBatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTabBarLayout = new javax.swing.GroupLayout(PanelTabBar);
        PanelTabBar.setLayout(PanelTabBarLayout);
        PanelTabBarLayout.setHorizontalGroup(
            PanelTabBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhamPha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThuVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelTabBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(btnNoiBat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTabBarLayout.setVerticalGroup(
            PanelTabBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNoiBat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhamPha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThuVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLive, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(PanelTabBar, java.awt.BorderLayout.LINE_START);

        PanelFooter.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        imageBaiHat.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\anh-bia-am-nhac2.jpg")); // NOI18N

        lbTenBaiHat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTenBaiHat.setForeground(new java.awt.Color(255, 255, 255));
        lbTenBaiHat.setText("Đi về nhàĐi về nhàĐi về nhà");
        lbTenBaiHat.setMaximumSize(new java.awt.Dimension(200, 20));
        lbTenBaiHat.setMinimumSize(new java.awt.Dimension(150, 22));

        lbTenCaSi.setForeground(new java.awt.Color(204, 204, 204));
        lbTenCaSi.setText("Đen Vâu");
        lbTenCaSi.setMaximumSize(new java.awt.Dimension(450, 16));

        btnMore.setBackground(new java.awt.Color(0, 0, 0));
        btnMore.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-more-30.png")); // NOI18N
        btnMore.setBorder(null);
        btnMore.setFocusPainted(false);
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTenBaiHat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenCaSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMore)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(lbTenBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbTenCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        lbThoiGianHienTai.setForeground(new java.awt.Color(255, 255, 255));
        lbThoiGianHienTai.setText("0:13");

        lbTongThoiGian.setForeground(new java.awt.Color(255, 255, 255));
        lbTongThoiGian.setText("5:11");

        progessTimeBaiHat.setValue(50);
        progessTimeBaiHat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progessTimeBaiHatMouseClicked(evt);
            }
        });

        btnRandom.setBackground(new java.awt.Color(0, 0, 0));
        btnRandom.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-random-30.png")); // NOI18N
        btnRandom.setBorder(null);
        btnRandom.setFocusPainted(false);
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnLoop.setBackground(new java.awt.Color(0, 0, 0));
        btnLoop.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-loop-30.png")); // NOI18N
        btnLoop.setBorder(null);
        btnLoop.setFocusPainted(false);
        btnLoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoopActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        btnPrevBaiHat.setBackground(new java.awt.Color(0, 0, 0));
        btnPrevBaiHat.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\prev.png")); // NOI18N
        btnPrevBaiHat.setBorder(null);
        btnPrevBaiHat.setFocusPainted(false);
        btnPrevBaiHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevBaiHatActionPerformed(evt);
            }
        });
        jPanel6.add(btnPrevBaiHat);

        btnPlayPause.setBackground(new java.awt.Color(0, 0, 0));
        btnPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-pause.png"))); // NOI18N
        btnPlayPause.setBorder(null);
        btnPlayPause.setFocusPainted(false);
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });
        jPanel6.add(btnPlayPause);

        btnNextMusic.setBackground(new java.awt.Color(0, 0, 0));
        btnNextMusic.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-next-30.png")); // NOI18N
        btnNextMusic.setBorder(null);
        btnNextMusic.setFocusPainted(false);
        btnNextMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextMusicActionPerformed(evt);
            }
        });
        jPanel6.add(btnNextMusic);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoop))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbThoiGianHienTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progessTimeBaiHat, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongThoiGian)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRandom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(progessTimeBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbThoiGianHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTongThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jPanel3.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        progessVolume.setForeground(new java.awt.Color(0, 204, 51));
        progessVolume.setValue(90);
        progessVolume.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                progessVolumeMouseDragged(evt);
            }
        });
        progessVolume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progessVolumeMouseClicked(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-speaker-30.png")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        btnMenuPhatKeTiep.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPhatKeTiep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu-music.png"))); // NOI18N
        btnMenuPhatKeTiep.setBorder(null);
        btnMenuPhatKeTiep.setFocusPainted(false);
        btnMenuPhatKeTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPhatKeTiepActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnKaraoke.setBackground(new java.awt.Color(0, 0, 0));
        btnKaraoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/micro.png"))); // NOI18N
        btnKaraoke.setBorder(null);
        btnKaraoke.setFocusPainted(false);
        btnKaraoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaraokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(btnKaraoke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progessVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPhatKeTiep)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKaraoke)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuPhatKeTiep)
                    .addComponent(jButton13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(progessVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);

        javax.swing.GroupLayout PanelFooterLayout = new javax.swing.GroupLayout(PanelFooter);
        PanelFooter.setLayout(PanelFooterLayout);
        PanelFooterLayout.setHorizontalGroup(
            PanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelFooterLayout.setVerticalGroup(
            PanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFooterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(PanelFooter, java.awt.BorderLayout.PAGE_END);

        PannelContainer.setBackground(new java.awt.Color(23, 15, 35));

        jPanel9.setBackground(new java.awt.Color(23, 15, 35));

        jButton1.setBackground(new java.awt.Color(23, 15, 35));
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-left-30.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tìm kiếm");

        btnTimKiem.setText("Tìm");
        btnTimKiem.setBorder(null);
        btnTimKiem.setFocusPainted(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\anh-bia-am-nhac2.jpg")); // NOI18N
        jButton15.setBorder(null);
        jButton15.setFocusPainted(false);

        jButton16.setBackground(new java.awt.Color(23, 15, 35));
        jButton16.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-setting-30.png")); // NOI18N
        jButton16.setBorder(null);
        jButton16.setFocusPainted(false);

        jButton17.setBackground(new java.awt.Color(23, 15, 35));
        jButton17.setIcon(new javax.swing.ImageIcon("D:\\Media\\Image\\Musicapp\\Icons\\icons8-bell-30.png")); // NOI18N
        jButton17.setBorder(null);
        jButton17.setFocusPainted(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        ipTimKiem.setBorder(null);
        ipTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ipTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ipTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jButton1))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelWrap.setBackground(new java.awt.Color(23, 15, 35));
        PanelWrap.setLayout(new java.awt.BorderLayout());

        PanelContent.setBackground(new java.awt.Color(23, 15, 35));
        PanelContent.setLayout(new java.awt.BorderLayout());
        PanelWrap.add(PanelContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PannelContainerLayout = new javax.swing.GroupLayout(PannelContainer);
        PannelContainer.setLayout(PannelContainerLayout);
        PannelContainerLayout.setHorizontalGroup(
            PannelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelWrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PannelContainerLayout.setVerticalGroup(
            PannelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelContainerLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelWrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PannelContainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progessTimeBaiHatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progessTimeBaiHatMouseClicked
        // TODO add your handling code here:
        int mouseX = evt.getX();
        int progressBarWidth = progessTimeBaiHat.getWidth();
        float percentage = (float) mouseX / progressBarWidth;
        System.out.println("Width" + String.valueOf(progressBarWidth));
        System.out.println("vi tri: " + String.valueOf(mouseX));
        System.out.println("data: " + String.valueOf(percentage));

        MyMusicPlayer.setTimeBaiHat(percentage);


    }//GEN-LAST:event_progessTimeBaiHatMouseClicked

    private void btnKhamPhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhamPhaActionPerformed
        // TODO add your handling code here:
        ShowPanel("KhamPha", new KhamPhaPanel());
        resetTabBarColor();
        btnKhamPha.setBackground(new Color(102, 102, 102));

    }//GEN-LAST:event_btnKhamPhaActionPerformed

    private void btnThuVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuVienActionPerformed
        // TODO add your handling code here:
        ShowPanel("ThuVien", new ThuVienPanel());
        resetTabBarColor();
        btnThuVien.setBackground(new Color(102, 102, 102));

    }//GEN-LAST:event_btnThuVienActionPerformed

    private void btnLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiveActionPerformed
        // TODO add your handling code here:
        ShowPanel("Live", new LivePanel());
        resetTabBarColor();
        btnLive.setBackground(new Color(102, 102, 102));

    }//GEN-LAST:event_btnLiveActionPerformed

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        // TODO add your handling code here:
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem option1 = new JMenuItem("Option 1");
        JMenuItem option2 = new JMenuItem("Option 2");
        JMenuItem option3 = new JMenuItem("Option 3");

        popupMenu.add(option1);
        popupMenu.add(option2);
        popupMenu.add(option3);

        popupMenu.show(btnMore, 0, -popupMenu.getHeight() - 70);
    }//GEN-LAST:event_btnMoreActionPerformed

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
        // TODO add your handling code here:

        if (MyMusicPlayer.isPlay) {
            MyMusicPlayer.pause();

        } else {
            MyMusicPlayer.resume();
        }

    }//GEN-LAST:event_btnPlayPauseActionPerformed

    private void progessVolumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progessVolumeMouseClicked
        // TODO add your handling code here:
        int mouseX = evt.getX();
        int progressBarWidth = progessVolume.getWidth();
        float percentage = (float) mouseX / progressBarWidth;

        int newData = (int) (percentage * 100);
        MyMusicPlayer.setVolume(newData);
    }//GEN-LAST:event_progessVolumeMouseClicked

    private void progessVolumeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progessVolumeMouseDragged
        // TODO add your handling code here:
        int mouseX = evt.getX();
        int progressBarWidth = progessVolume.getWidth();
        float percentage = (float) mouseX / progressBarWidth;

        int newData = (int) (percentage * 100);
        MyMusicPlayer.setVolume(newData);
    }//GEN-LAST:event_progessVolumeMouseDragged

    private void btnNextMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextMusicActionPerformed
        // TODO add your handling code here:
        MyMusicPlayer.nextBaiHat();
    }//GEN-LAST:event_btnNextMusicActionPerformed

    private void btnPrevBaiHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevBaiHatActionPerformed
        // TODO add your handling code here:
        MyMusicPlayer.preBaiHat();
    }//GEN-LAST:event_btnPrevBaiHatActionPerformed

    private void btnLoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoopActionPerformed
        // TODO add your handling code here:
        if (MyMusicPlayer.isLoop) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-loop.png"));
            btnLoop.setIcon(icon);
        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-loop-active.png"));
            btnLoop.setIcon(icon);
        }
        MyMusicPlayer.isLoop = !MyMusicPlayer.isLoop;


    }//GEN-LAST:event_btnLoopActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
        if (MyMusicPlayer.isRandom) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-random.png"));
            btnRandom.setIcon(icon);
        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-random-active.png"));
            btnRandom.setIcon(icon);
            MyMusicPlayer.getListRandom();
        }
        MyMusicPlayer.isRandom = !MyMusicPlayer.isRandom;
    }//GEN-LAST:event_btnRandomActionPerformed


    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String keyword = ipTimKiem.getText();
        if (!keyword.isEmpty()) {
            ShowPanel("TimKiem", new TimKiemPanel(keyword));
        }


    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnMenuPhatKeTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPhatKeTiepActionPerformed
        // TODO add your handling code here:
        if (isMenuPhatKeTiep) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/menu-music.png"));
            btnMenuPhatKeTiep.setIcon(icon);

            JPanel phatKeTiep = new PhatKeTiepPanel();
            PanelWrap.remove(1);
            PanelWrap.revalidate();
            PanelWrap.repaint();
        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/menu-music-active.png"));
            btnMenuPhatKeTiep.setIcon(icon);

            JPanel phatKeTiep = new PhatKeTiepPanel();
            PanelWrap.add(phatKeTiep, BorderLayout.EAST);
            PanelWrap.revalidate();
            PanelWrap.repaint();
        }
        isMenuPhatKeTiep = !isMenuPhatKeTiep;

    }//GEN-LAST:event_btnMenuPhatKeTiepActionPerformed

    private void btnKaraokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaraokeActionPerformed
        // TODO add your handling code here:
        if (isKaraoke) {
            ShowPanel(oldPanel, null);
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/micro.png"));
            btnKaraoke.setIcon(icon);
            isKaraoke = false;

        } else {
            ShowPanel("Karaoke", new KaraokePanel());
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/micro-active.png"));
            btnKaraoke.setIcon(icon);
            isKaraoke = true;
        }


    }//GEN-LAST:event_btnKaraokeActionPerformed

    private void btnNoiBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiBatActionPerformed
        // TODO add your handling code here:
        ShowPanel("NoiBat", null);
        resetTabBarColor();
        btnNoiBat.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnNoiBatActionPerformed

    private void ipTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipTimKiemActionPerformed
        // TODO add your handling code here:
        String keyword = ipTimKiem.getText();
        if (!keyword.isEmpty()) {
            ShowPanel("TimKiem", new TimKiemPanel(keyword));
        }
    }//GEN-LAST:event_ipTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ShowPanel(oldPanel, null);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void resetTabBarColor() {
        btnKhamPha.setBackground(new Color(51, 0, 51));
        btnThuVien.setBackground(new Color(51, 0, 51));
        btnLive.setBackground(new Color(51, 0, 51));
        btnNoiBat.setBackground(new Color(51, 0, 51));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    public static javax.swing.JPanel PanelFooter;
    private javax.swing.JPanel PanelTabBar;
    public static javax.swing.JPanel PanelWrap;
    private javax.swing.JPanel PannelContainer;
    public static javax.swing.JButton btnKaraoke;
    private javax.swing.JButton btnKhamPha;
    private javax.swing.JButton btnLive;
    private javax.swing.JButton btnLoop;
    private javax.swing.JButton btnMenuPhatKeTiep;
    private javax.swing.JButton btnMore;
    private javax.swing.JButton btnNextMusic;
    private javax.swing.JButton btnNoiBat;
    public static javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnPrevBaiHat;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnThuVien;
    private javax.swing.JButton btnTimKiem;
    public static javax.swing.JLabel imageBaiHat;
    private javax.swing.JTextField ipTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lbTenBaiHat;
    public static javax.swing.JLabel lbTenCaSi;
    public static javax.swing.JLabel lbThoiGianHienTai;
    public static javax.swing.JLabel lbTongThoiGian;
    public static javax.swing.JProgressBar progessTimeBaiHat;
    public static javax.swing.JProgressBar progessVolume;
    // End of variables declaration//GEN-END:variables
}
