/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import javax.swing.ImageIcon;
import helpers.Utils;
import java.awt.BorderLayout;
import javax.swing.JLabel;

/**
 *
 * @author tranv
 */
public class CircleImage extends javax.swing.JPanel {

    public String url;
    /**
     * Creates new form CircleImagePanel
     */
    public CircleImage(String url, int w,int h) {
        initComponents();
        setPreferredSize(new Dimension(w,h));
        setLayout(new BorderLayout());
        
        JLabel img = new JLabel();
        ImageIcon icon = Utils.getImageBaiHat(url, w, h);
        img.setIcon(icon);
        
        add(img);
        
        this.url = url;
    }

//    @Override
//    protected void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        drawCircularImage(g);
//    }
//
//    public void drawCircularImage(Graphics g) {
//        int w = getWidth();
//        int h = getHeight();
//
//        // Tạo hình tròn
//        Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, w, h); // Thay đổi kích thước và vị trí nếu cần
//
//        // Sử dụng hình tròn như một clip để cắt ảnh
//        Graphics2D g2 = (Graphics2D) g;
//        g2.setClip(circle);
//
//        ImageIcon img = Utils.getImageBaiHat(url, w, h);
//
//        // Vẽ ảnh trong phạm vi hình tròn
//        g.drawImage(img.getImage(), 0, 0, null);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(23, 15, 35));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
