/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Interface.UpdateListMusic;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.BaiHat;

/**
 *
 * @author tranv
 */
public class FilterListMusic extends javax.swing.JPanel {

    ArrayList<BaiHat> listBH;
    UpdateListMusic ulm;

    /**
     * Creates new form FilterListMusic
     */
    public FilterListMusic(ArrayList<BaiHat> listBH, UpdateListMusic ulm) {
        initComponents();
        this.listBH = listBH;
        this.ulm = ulm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTen = new javax.swing.JComboBox<>();
        cbThoiGian = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();

        setBackground(new java.awt.Color(23, 15, 35));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)), "Bộ lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên");

        cbTen.setBackground(new java.awt.Color(0, 255, 255));
        cbTen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Từ A - Z", "Từ Z - A" }));
        cbTen.setToolTipText("");

        cbThoiGian.setBackground(new java.awt.Color(255, 255, 0));
        cbThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dài nhất", "Ngắn nhất" }));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thời gian");

        btnChon.setBackground(new java.awt.Color(0, 255, 102));
        btnChon.setText("Chọn");
        btnChon.setFocusPainted(false);
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChon))
                    .addComponent(jLabel2))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        sapXepTheoTen();

        sapXepTheoThoiGian();
        

        ulm.updateListMusic();
    }//GEN-LAST:event_btnChonActionPerformed

    public void sapXepTheoTen() {
        String ten = cbTen.getSelectedItem().toString();
        if (ten.equals("None")) {
            return;
        }

        if (ten.equals("Từ A - Z")) {
            Collections.sort(listBH, new Comparator<BaiHat>() {
                @Override
                public int compare(BaiHat bh1, BaiHat bh2) {
                    return bh1.getTenBaiHat().compareTo(bh2.getTenBaiHat());
                }
            });
        } else {
            Collections.sort(listBH, new Comparator<BaiHat>() {
                @Override
                public int compare(BaiHat bh1, BaiHat bh2) {
                    return bh2.getTenBaiHat().compareTo(bh1.getTenBaiHat());
                }
            });
        }

    }

    public void sapXepTheoThoiGian() {
        String thoiGian = cbThoiGian.getSelectedItem().toString();
        if (thoiGian.equals("None")) {
            return;
        }

        if (thoiGian.equals("Dài nhất")) {
            Collections.sort(listBH, new Comparator<BaiHat>() {
                @Override
                public int compare(BaiHat bh1, BaiHat bh2) {
                    return bh1.getThoiGian() < bh2.getThoiGian() ? 1 : -1;
                }
            });
        } else {
            Collections.sort(listBH, new Comparator<BaiHat>() {
                @Override
                public int compare(BaiHat bh1, BaiHat bh2) {
                    return bh2.getThoiGian() < bh1.getThoiGian() ? 1 : -1;
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JComboBox<String> cbTen;
    private javax.swing.JComboBox<String> cbThoiGian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
