/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import component.CircleImagePanel;
import gson.LiveItem;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import frame.MainJFrame;
import screen.ChiTietLivePanel;

/**
 *
 * @author tranv
 */
public class ItemLivePanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemLivePanel
     */
    public ItemLivePanel(LiveItem live) {
        initComponents();
        
        JPanel pn = new CircleImagePanel(live.getAvatar(),150, 150);
        
         pn.addMouseListener(new  MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                MainJFrame.ShowPanelNoHistory("ChiTietLive", new ChiTietLivePanel(live.getIdRoom(), live.getAvatar()));
            }
            
        });
        
        add(pn);
        
        JPanel pn2 = new JPanel();
        pn2.setBackground(new Color(23,15,35));
        FlowLayout fl = new FlowLayout();
        fl.setAlignment(FlowLayout.CENTER);
        pn2.setLayout(fl);

        JLabel lb = new JLabel();
        lb.setText(live.getNameRoom());
        lb.setForeground(Color.WHITE);

        pn2.add(lb);

        add(pn2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
