/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import frame.MainJFrame;
import services.MyMusicPlayer;

/**
 *
 * @author tranv
 */
public class ModelHenGio extends javax.swing.JPanel {

    public static int phut_hengio = 0;
    public static int giay_hengio = 0;

    public static Thread threadHenGio;

    /**
     * Creates new form ModelHenGio
     */
    public ModelHenGio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jsPhut = new javax.swing.JSpinner();
        jsGiay = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hẹn giờ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Thời gian:");
        jLabel2.setToolTipText("");

        jsPhut.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsPhut.setFocusable(false);

        jsGiay.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jsGiay.setFocusable(false);

        jLabel3.setText("phút");

        jLabel4.setText("giây");

        btnOk.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOk)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsPhut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jsPhut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
    public void xuLyHenGio() {
        int phut = (int) jsPhut.getValue();
        int giay = (int) jsGiay.getValue();
        System.out.printf("Phut: %d, giay: %d", phut, giay);

        if (giay != 0 || phut != 0) {
            phut_hengio = phut;
            giay_hengio = giay;

            if (threadHenGio != null && threadHenGio.isAlive()) {
                threadHenGio.interrupt();
            }

            threadHenGio = new Thread(() -> {
                while (true) {
                    try {
                        Thread.sleep(1000);
                        giay_hengio--;
                        if (giay_hengio < 0) {
                            phut_hengio--;
                            giay_hengio = 59;
                        }

                        if (phut_hengio == 0 && giay_hengio == 0) {
                            MyMusicPlayer.pause();
                            MainJFrame.lblHenGio.setText("");
                            break;
                        } else {
                            String strGiay = giay_hengio < 10 ? "0" + giay_hengio : "" + giay_hengio;
                            MainJFrame.lblHenGio.setText(String.format("%d:%s", phut_hengio, strGiay));
                        }

                    } catch (InterruptedException ex) {
                        break;
                    }

                }
            });

            threadHenGio.start();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jsGiay;
    private javax.swing.JSpinner jsPhut;
    // End of variables declaration//GEN-END:variables
}
