/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import gson.BaiHat;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import component.PhatKeTiepPanel;
import services.MyMusicPlayer;
import services.utils;

/**
 *
 * @author tranv
 */
public class MiniAppFrame extends javax.swing.JFrame {

    public static boolean isOpen = false;
    private boolean isShowPhatKeTiep = false;

    /**
     * Creates new form MiniAppFrame
     */
    public MiniAppFrame() {
//        setUndecorated(true);
        initComponents();
        setAlwaysOnTop(true);
        setTitle("Đang phát");
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-app.jpg"));
        setIconImage(icon.getImage());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        loadGiaoDienBaiHat();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                isOpen = false;
            }

        });

        pack();

    }

    public void loadGiaoDienBaiHat() {
        if (MyMusicPlayer.dsBaiHat != null && MyMusicPlayer.dsBaiHat.size() != 0) {
            BaiHat bh = MyMusicPlayer.dsBaiHat.get(MyMusicPlayer.position);

            new Thread(() -> {
                ImageIcon anh = utils.getImageBaiHat(bh.getAnhBia(), 50, 50);
                imgBaiHat.setIcon(anh);
            }).start();

            lblTenCaSi.setText(utils.getTenCaSi(bh));
            lblTenBaiHat.setText(bh.getTenBaiHat());

            if (MyMusicPlayer.isPlay) {
                ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-pause.png"));
                btnPause.setIcon(icon);
            } else {
                ImageIcon icon = new ImageIcon(getClass().getResource("/icon/icon-play.png"));
                btnPause.setIcon(icon);
            }

            if (isShowPhatKeTiep) {
                ImageIcon icon = new ImageIcon(getClass().getResource("/icon/menu-music-active.png"));
                btnPhatKeTiep.setIcon(icon);
            } else {
                ImageIcon icon = new ImageIcon(getClass().getResource("/icon/menu-music.png"));
                btnPhatKeTiep.setIcon(icon);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imgBaiHat = new javax.swing.JLabel();
        lblTenBaiHat = new javax.swing.JLabel();
        lblTenCaSi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnShowMainApp = new javax.swing.JLabel();
        btnPrev = new javax.swing.JLabel();
        btnPause = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnPhatKeTiep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(23, 15, 35));

        lblTenBaiHat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenBaiHat.setForeground(new java.awt.Color(255, 255, 255));

        lblTenCaSi.setForeground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(23, 15, 35));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnShowMainApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons-device-20.png"))); // NOI18N
        btnShowMainApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowMainApp.setMaximumSize(new java.awt.Dimension(40, 20));
        btnShowMainApp.setPreferredSize(new java.awt.Dimension(40, 20));
        btnShowMainApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMainAppMouseClicked(evt);
            }
        });
        jPanel3.add(btnShowMainApp);

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/prev.png"))); // NOI18N
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });
        jPanel3.add(btnPrev);

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-pause.png"))); // NOI18N
        btnPause.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPauseMouseClicked(evt);
            }
        });
        jPanel3.add(btnPause);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-next-30.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        jPanel3.add(btnNext);

        btnPhatKeTiep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPhatKeTiep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-playlist.png"))); // NOI18N
        btnPhatKeTiep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPhatKeTiep.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPhatKeTiep.setMaximumSize(new java.awt.Dimension(40, 20));
        btnPhatKeTiep.setPreferredSize(new java.awt.Dimension(40, 20));
        btnPhatKeTiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPhatKeTiepMouseClicked(evt);
            }
        });
        jPanel3.add(btnPhatKeTiep);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imgBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenBaiHat)
                    .addComponent(lblTenCaSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblTenBaiHat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTenCaSi))
                        .addComponent(imgBaiHat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMainAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMainAppMouseClicked
        // TODO add your handling code here:
        MiniAppFrame.isOpen = false;
        dispose();
        Main.rootFrame.setVisible(true);
    }//GEN-LAST:event_btnShowMainAppMouseClicked

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        MyMusicPlayer.preBaiHat();
        loadGiaoDienBaiHat();
        resetPhatKeTiep();
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        MyMusicPlayer.nextBaiHat();
        loadGiaoDienBaiHat();
        resetPhatKeTiep();
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPauseMouseClicked
        // TODO add your handling code here:
        if (MyMusicPlayer.isPlay) {
            MyMusicPlayer.pause();
        } else {
            MyMusicPlayer.resume();
        }
        loadGiaoDienBaiHat();
        resetPhatKeTiep();
    }//GEN-LAST:event_btnPauseMouseClicked

    private void btnPhatKeTiepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhatKeTiepMouseClicked
        // TODO add your handling code here:
        isShowPhatKeTiep = !isShowPhatKeTiep;
        loadGiaoDienBaiHat();

        resetPhatKeTiep();

    }//GEN-LAST:event_btnPhatKeTiepMouseClicked

    public void resetPhatKeTiep() {
        if (isShowPhatKeTiep) {
            setSize(428, 400);
            JPanel pn = new PhatKeTiepPanel(true);
            jPanel1.add(pn, BorderLayout.CENTER);

        } else {
            setSize(428, 90);
            try {
                jPanel1.remove(1);
            } catch (Exception e) {
            }

        }
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPause;
    private javax.swing.JLabel btnPhatKeTiep;
    private javax.swing.JLabel btnPrev;
    private javax.swing.JLabel btnShowMainApp;
    private javax.swing.JLabel imgBaiHat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTenBaiHat;
    private javax.swing.JLabel lblTenCaSi;
    // End of variables declaration//GEN-END:variables
}
